spring.application.name=SpringEcom

spring.datasource.url=jdbc:postgresql://localhost:5432/telusko2
spring.datasource.username=postgres
spring.datasource.password=Makcofighter29!
spring.jpa.hibernate.ddl-auto=update